### ISSUE TITLE
Unable to generate forms for combined schemas

### ISSUE THREAD

**Issue by gastonche** [Limenius/liform-react#10]
I have setup this liform library within my project and it works fine, (without styling though). However some schemas, (like the one i need to use it for) don't generate any form, just a submit button. I don't understand this behaviour. But i have noticed it happens with all schemas I have tried that have schema combination key words like anyOff, allOf, oneOf.
A sample form of a schema that fails is this:
```javascript
   {
  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "state": {
          "type": "string"
        }
      },
      "required": [
        "street_address",
        "city",
        "state"
      ]
    }
  },
  "allOf": [
    {
      "$ref": "#/definitions/address"
    },
    {
      "properties": {
        "type": {
          "enum": [
            "residential",
            "business"
          ]
        }
      }
    }
  ]
}
```

**Comment by nacmartin** [comment]
Hi. Thanks for reporting this. This is an interesting point.

First, the library was missing support for `$ref`s, so I have added it.

Second, I think that`allOf` is the only keyword from the set of `allOf` `anyOf` `oneOf` that we could possible support. Using one of the other two would mean that the generator must choose which one is the one that should generate the form for.

How would `anyOf` or `oneOf` work? should it be better to not support them, or should it select somehow, with a selector of some kind, which is the definition to use?

**Comment by gastonche** [comment]
I think `anyOf` and `oneOf` should be treated the same as `allOf` while the form is being generated. The  difference comes while validating. If the form for all the combined schema are generated, then in the case of say `oneOf` validation will fail if the user fills all the forms, and the appropriate error thrown. that way we don't stress on choosing which to select

**Comment by nacmartin** [comment]
Ok, but in your case we have all the information to generate a form. It will contain 4 properties: `type`, `street_address`, `city` and `state`. But what about this case?

````
{
  "anyOf": [
    { "type": "string", "maxLength": 5 },
    { "type": "string", "enum": ["something", "something_else"] }
  ]
}
````

In this case the widget can be either a string or a choice, and we don't know which one to use.

**Comment by gastonche** [comment]
with the above situation, if the lib generated a string input and a select list, then the uses any. if all are filled it is correct, if just one is filled it is correct. because the lib looking at the second subschema will automatically generate a select and a text input for the first. I think that solves it to an extent!

**Comment by nacmartin** [comment]
mmm. Ok, it can be tried. 🤔 . Anyways, if this is end up confusing somehow it will only affect the schemas that we are already not supporting, so it would be an improvement, I guess.

**Comment by gastonche** [comment]
Yeah, I cloned the repo already, I will start going through, hopefully I will get upto speed soon enough to try out any other option.

**Comment by nacmartin** [comment]
In case you are digging into this note that the current implementation of $ref is not definitive because it precompiles the tree, which is simple, but it will fail if the $ref are recursive ($ref referring to itself), so at some point it should be replaced by a better solution. The API shouldn't change and the current implementation provides an improvement, so I have merged it, but there should be a better way of doing it.

**Comment by mfulton26** [comment]
For `"oneOf"` it seems to me that each fieldset could be displayed inside of a radio set so that the user can specify which one to use. e.g.

```json
{
  "anyOf": [
    { "type": "string", "maxLength": 5 },
    { "type": "string", "enum": ["something", "something_else"] }
  ]
}
```

This might generate something similar to the following (but with CSS and other improvements):

```html
<div>
  <input type="radio" name="oneOf">
  <fieldset>
    <input type="text" maxlength="5">
  </fieldset>
</div>
<div>
  <input type="radio" name="oneOf">
  <fieldset>
    <select>
      <option>something</option>
      <option>something_else</option>
    </select>
  </fieldset>
</div>
```

**Comment by gastonche** [comment]
I have added support for oneOf successfully to the library and will love to submit a PR soon, however, I need some propositions, I need to add support for allOf and anyOf. I will love to some ideas on how allOf should be handled. Currently oneOf is handled with a select control, so changing the choice brings up the new schema and you can enter the values you want.
For allOf i first Implemented it  by justdisplaying all the subschemas, but it's not accurate as the allOf may generate a funny schema in certain cases like this 
```
{
  "allOf": [
    { "type": "string" },
    { "maxLength": 5 }
  ]
}
```
I need some ideas in order to proceed with this implementations

**Comment by nacmartin** [comment]
Nice!

About allOf, what about deep merging all the elements in the array in a single object?

Your example would be:

````
{ "type": "string",
  "maxLenght": 5 }
````

And for instance this one:

```
{
  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  },

  "allOf": [
    { "$ref": "#/definitions/address" },
    { "properties": {
        "type": { "enum": [ "residential", "business" ] }
      }
    }
  ]
}
```

would become:

````
{
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" },
       "type": { "enum": [ "residential", "business" ] }
      },
      "required": ["street_address", "city", "state"]
}
````

A form generated with the merge would validate "allOf" the elements of the array. Would this work?

**Comment by gastonche** [comment]
Thanks @nacmartin taht would work out great, I'll implement that this night and submit a PR for you to check it out by tomorrow
. Then what about the anyOf scenario, I was think of just generating all the subschemas so that the user fills any and allows what they can't fill?

**Comment by nacmartin** [comment]
If it works, I am for it... I don't know of other solutions in other generators. It is tricky to do this in a generator. Anyways, if the user has the possibility to manage this with themes customizing the widgets somehow, whoever has a special case that is different of what you write, can write his own widget and have the UI that he prefers.

**Comment by gastonche** [comment]
@nacmartin okay. I will get back to you soon, once I have done something on that.
Thanks again
