### ISSUE TITLE
Translate errors

### ISSUE THREAD

**Issue by LoicGoyet** [Limenius/liform-react#15]
Hi, after digging a lot into the code, I do not have any clues for translating the errors printed after validation, and there is no parts in the documentation for this. Could you tell us what is the easiest way to translate thoses errors ? thanks a lot

**Comment by nacmartin** [comment]
You can pass your own validator to Liform 
https://github.com/Limenius/liform-react/blob/b2490126e38b7faeb2858ad9ebb73064e4363f19/src/index.js#L30

A possibility would be to pass a modified version of `buildSyncValidation` that uses ajv-i18n 
https://github.com/Limenius/liform-react/blob/b2490126e38b7faeb2858ad9ebb73064e4363f19/src/buildSyncValidation.js#L72

https://github.com/epoberezkin/ajv-i18n#usage

**Comment by nacmartin** [comment]
I've just remembered that I wrote an example of this here https://github.com/nacmartin/liform-daniel-example/blob/master/src/js/Example4.js#L65

**Comment by grimpows** [comment]
with the current buildSyncValidation, why dont add a locale parameter ?
i simply modified the actual buildSyncValidation to : 
````
const buildSyncValidation = (schema, ajvParam = null, locale = null ) => {
            let ajv = ajvParam
            if (ajv === null) {
                ajv = new Ajv({ errorDataPath: 'property', allErrors: true, jsonPointers: true })
            }
            return values => {
                const valid = ajv.validate(schema, values)
                if (valid) {
                    return {}
                }
                const ajvErrors = ajv.errors
                if(locale !== null){ //this if is the only thing added with the local props
                    var validate = ajv.compile(schema);
                    localize[locale](validate.errors) 
                }
                
                
                let errors = ajvErrors.map((error) => {
                    return setError(error, schema)
                })
                // We need at least two elements
                errors.push({})
                errors.push({})
                
                return merge.all(errors)
            }

        }

````
