### ISSUE TITLE
Using Format to genarate form widget

### ISSUE THREAD

**Issue by gastonche** [Limenius/liform-react#21]
I have been taking a look at json-schema and liform-react. I know it is possible to specify a format for a field. The current implementation of liform-react utilises the type property of every schema-property to determine the widget to make use of. However the use the format property together with the type property will make the choosing of appropriate widget more effective. For example, 
```javascript
"properties": {
                    "contents": {
                        "description": "content (plain-text only)", 
                        "format": "textarea", 
                        "propertyOrder": 3, 
                        "type": "string"
                    }, 
                    "mode": {
                        "default": "0644", 
                        "description": "filesystem permissions", 
                        "maxLength": 4, 
                        "minLength": 3, 
                        "pattern": "^[0-7]*$", 
                        "propertyOrder": 2, 
                        "type": "string"
                    }, 
                    "path": {
                        "description": "filesystem path", 
                        "propertyOrder": 1, 
                        "type": "string"
                    }
                }
```

from the above schema,  we can see that using the type property of content, path and mode will give us an appropriate widget, however what if we did have a textarea widget and we made us of the format property of content to choose the widget. That'd more efficient.
My proposal is that we check for the format property and return if a valid widget is found for it, else we fallback to using the type property. This double checking will help increase our widget choice efficiency.

**Comment by nacmartin** [comment]
We can already do this. If you have a property

```` 
 'color': { 'type':'string', 'widget': 'color', 'title': 'In which color' },
````

It will look for the widget `color`. If it was 

```` 
 'color': { 'type':'string', 'title': 'In which color' },
````

It would use the widget `string` instead.

**Comment by gastonche** [comment]
I was following the json-schema standards following this [docs](http://json-schema.org/latest/json-schema-validation.html#rfc.section.8), and i believe it's going to be more standards to enable the format property too for this check given that most people may already have followed those standards and setup their schema with the format property.

**Comment by nacmartin** [comment]
Ok, it may be good idea:

 If `widget` is present, use `widget`. 

Otherwise: If `format` is present, then use `format`.

Otherwise: use `type`.

Would that be ok?

**Comment by gastonche** [comment]
Yes, that will be okay, I will clean up the code I have written for this and submit a PR by the end of the week.
