### ISSUE TITLE
Getting [object Object] as text input value with simple array of strings

### ISSUE THREAD

**Issue by nottoseethesun** [Limenius/liform-react#24]
I've followed the code through in the debugger, but cannot find a way to stop `liform-react` from displaying '[object Object]' as the html text input element value:

```           
        "columns": {
                "type": "array",
                "minItems": 1,
                "items": {
                  "type": "string"
                }
              },
```

The text input value simply needs to be the empty string.  I have no custom code that does anything like `push({})`.

Any hints?

**Comment by nacmartin** [comment]
It should be fixed in v0.6.6 and master. Thanks for reporting, @nottoseethesun
