### ISSUE TITLE
Customize the Submit Button

### ISSUE THREAD

**Issue by leuction** [Limenius/liform-react#36]
I want to wrap this library with my customized component. However, I don't know how to customize the submit button.

Is there any way that I can customize the submit button without changing the source code?

Thanks.

**Comment by m3doune** [comment]
Hello I've already made a pull request for this purpose, I'm waiting for it's integration.

**Comment by leuction** [comment]
@m3doune I think that might not be a good way to do that. If I want to integrate a button from material-ui or other ui libs. customize only the classname will not solve that problem. I think pass the button as children might be a better way to do that. just like what react-jsonschema-form did.

**Comment by m3doune** [comment]
@leuction you're right! Pass the button as a children is better.

**Comment by leuction** [comment]
@m3doune I have posted another PR. But it seems that this repo is dead?

**Comment by nacmartin** [comment]
It is not dead, but I am very busy :/ I have this on my mind quite often, believe me, trying to find some time.

**Comment by leuction** [comment]
Thank you for building this great library. I think it might be great to add the Button to the theme, so that I can install another theme from npm. That might be better than pass it as children.

**Comment by leuction** [comment]
I found out that I can customize the form by pass a props call baseForm.

```javascript
<Liform
  ...
  baseForm={BaseForm} // you can get this from ./src/index.js
  ...
/>

```
