### ISSUE TITLE
"type": "number fails validation

### ISSUE THREAD

**Issue by cjek420** [Limenius/liform-react#6]
"type": "number" or "type": "integer" displays the correct UI only allows a number to be inputed. But, it always fails the validate with "should be number". A quick test using ajv the validation for a number works.

You can see the issue at https://limenius.github.io/liform-react/#/examples/all-widgets just goto the number field.

Thanks,

Curtis

**Comment by nacmartin** [comment]
Thanks for reporting this :+1:

Fixed in v0.5.14 5530c0183a33209e8870443b646fb54360805b1c
