### ISSUE TITLE
Layout and initial values

### ISSUE THREAD

**Issue by CedrikWinter** [Limenius/liform-react#8]
Bonjour,

It's more a question than an issue, but there is not tag for **liform** on _stackoverflow_... So here is my question : http://stackoverflow.com/q/43979726/2470352

Merci

**Comment by CedrikWinter** [comment]
Answer in the slack no "schema.title" => use null in `renderField`

**Comment by nacmartin** [comment]
Thanks for reporting this. I have updated the docs accordingly.
