### ISSUE TITLE
What about $ref ?

### ISSUE THREAD

**Issue by CedrikWinter** [Limenius/liform-react#9]
Bonjour,

I'm trying **$ref** feature from Ajv, [see example](http://json-schema.org/example2.html#the-full-entry-schema).
Actually, what I am really trying to do is to generate a **dynamic form**. Dynamic because a select box tells (onChange event) what are the next fields to display... Any idea ?

Merci,
Cédrik

**Comment by nacmartin** [comment]
I have to play with this a bit to give a meaningful answer. I am out of
town currently, but I will try to answer during the weekend.

**Comment by nacmartin** [comment]
Hi. These are two separated topics (that can be combined).

This library doesn't support refs currently. Although it could be a nice addition, as it is part of the json-schema specification. They would ve handy to avoid repeating pieces of the schema.

However, a dynamic form like the one you describe doesn't need $refs, it is a matter of rendering conditionally. For this case, what I would do is to create my own widget. Depending of the structure of the values that you want to produce (your schema), it may vary, but one possible representation would be this:

https://github.com/nacmartin/liform-dynamic/blob/master/src/js/Example1.js

The example is online here: https://nacmartin.github.io/liform-dynamic/

We are using here the formValueSelector property of redux-form, [to access a value of the form](https://github.com/nacmartin/liform-dynamic/blob/ee7a9b73825a60fdbedaf60247403f7ce1029b33/src/js/Example1.js#L26).

Then, [in a custom widget](https://github.com/nacmartin/liform-dynamic/blob/ee7a9b73825a60fdbedaf60247403f7ce1029b33/src/js/Example1.js#L12), we render conditionally fields depending on the value of the other field.

Does this make sense for you?

**Comment by CedrikWinter** [comment]
It works perfectly ! Thank you very much.
With your code, I have discovered that an **whole** _"schema object"_ can be rendered with a widget. I thought that widgets were only for fields... 
It helped ! Thank you again.

**Comment by nacmartin** [comment]
Just a quick note. The library supports $refs now.
